# -*- coding: utf-8 -*-
"""Python  TASK - 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4BnPudj1bAp74S0JwX6Aq7RSkzbAkRf
"""

import os
import re
import shutil
import requests

# -----------------------------------
# TASK 1 : Get Website Title
# -----------------------------------

print("STEP 1 : WEBSITE TITLE")

# Website link
url = "https://example.com"

# Get webpage data
response = requests.get(url)

# Store webpage content
html = response.text

# Find title using regex
title = re.search(r"<title>(.*?)</title>", html)

# Check if title exists
if title:

    website_title = title.group(1)

    print("Website Title:", website_title)

    # Save title in file
    file = open("title.txt", "w")
    file.write(website_title)
    file.close()

    print("Title saved in title.txt")

print("\n")


# -----------------------------------
# TASK 2 : Extract Email Addresses
# -----------------------------------

print("STEP 2 : EMAIL EXTRACTION")

# Create sample text file
sample = open("data.txt", "w")

sample.write("""
Contact us at support@gmail.com
or help@yahoo.com
""")

sample.close()

# Read file
file = open("data.txt", "r")

text = file.read()

# Find emails
emails = re.findall(r"\S+@\S+", text)

print("Emails Found:", emails)

# Save emails to another file
output = open("emails.txt", "w")

for email in emails:

    output.write(email + "\n")

output.close()

file.close()

print("Emails saved in emails.txt")

print("\n")


# -----------------------------------
# TASK 3 : Move JPG Files
# -----------------------------------

print("STEP 3 : MOVE JPG FILES")

# Create folders
os.mkdir("source_folder")
os.mkdir("destination_folder")

# Create dummy jpg file
photo = open("source_folder/photo.jpg", "w")

photo.write("image file")

photo.close()

# Check files in source folder
files = os.listdir("source_folder")

for file in files:

    # Check jpg files
    if file.endswith(".jpg"):

        # Move file
        shutil.move(
            "source_folder/" + file,
            "destination_folder/" + file
        )

        print(file, "moved successfully")

print("\nALL TASKS COMPLETED")