# -*- coding: utf-8 -*-
"""Python  TASK - 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdIALVPfUXNoigDGqZ4dRlb3Cg44-gGq
"""

# Stock prices dictionary
stocks = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGLE": 150
}

# User input
stock_name = input("Enter stock name: ").upper() # Convert input to uppercase
quantity = int(input("Enter quantity: "))

# Calculate total investment
total = stocks[stock_name] * quantity

# Display result
print("Total Investment Value =", total)

# Save result to file
file = open("portfolio.txt", "w")
file.write("Stock: " + stock_name + "\n")
file.write("Quantity: " + str(quantity) + "\n")
file.write("Total Value: " + str(total))
file.close()

print("Data saved in portfolio.txt")