# -*- coding: utf-8 -*-
"""Python  TASK - 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9iLg1Hlw_yoZ4otWtlU_vv1Hjnuky55
"""

# Chatbot function
def chatbot():

    while True:

        # User input
        user = input("You: ").lower()

        # Bot replies
        if user == "hello":
            print("Bot: Hi!")

        elif user == "how are you":
            print("Bot: I'm fine, thanks!")

        elif user == "bye":
            print("Bot: Goodbye!")
            break

        else:
            print("Bot: I don't understand.")

# Run chatbot
chatbot()